### ISSUE TITLE
请问服务端会开源吗

### ISSUE THREAD

**Issue by YuGer26** [CNLHB/ssk-hfb#2]
I LIKE IT ，光看UI就足够精美了，这个服务端如何部署呢

**Comment by CNLHB** [comment]
后端是基于SpringBoot写的，现在还没整理好，后面会开源服务端代码，部署起来也是非常简单的，这是后台管理的页面也可以看一下哦http://ssk.xquery.cn

**Comment by CNLHB** [comment]
> 我喜欢它，光看ui就足够精美了，这个服务端如何部署呢
后端是基于SpringBoot写的，现在还没整理好，后面会开源服务端代码，部署起来也是非常简单的，这是后台管理的页面也可以看一下哦http://ssk.xquery.cn

**Comment by YuGer26** [comment]
好的哦，感谢大佬回复
