### ISSUE TITLE
请问会开源后端和数据库文件吗

### ISSUE THREAD

**Issue by pengp25** [CNLHB/ssk-hfb#4]
看了前端，觉得做得挺好看的hhh，用uniapp做跨平台应用挺好的，请问近期有开源后端和数据库文件的计划吗，想学习一下~

**Comment by CNLHB** [comment]
> 
> 
> 看了前端，觉得做得挺好看的hhh，用uniapp做跨平台应用挺好的，请问近期有开源后端和数据库文件的计划吗，想学习一下~

**Comment by CNLHB** [comment]
> 
> 
> 看了前端，觉得做得挺好看的hhh，用uniapp做跨平台应用挺好的，请问近期有开源后端和数据库文件的计划吗，想学习一下~
后端代码的话，需要整理，可能要一段时间，数据库文件我可以重新提交一下。

**Comment by pengp25** [comment]
好的期待，谢谢~

> > 看了前端，觉得做得挺好看的hhh，用uniapp做跨平台应用挺好的，请问近期有开源后端和数据库文件的计划吗，想学习一下~
> > 后端代码的话，需要整理，可能要一段时间，数据库文件我可以重新提交一下。
