### ISSUE TITLE
您好，请问会开源后端源码

### ISSUE THREAD

**Issue by zhangzhangzhangdada** [CNLHB/ssk-hfb#5]
您好，大佬，研究了您的项目，觉得特体功能特别棒，很值得学习。看了接口文档和数据库，想请问下，您会开源后端的代码吗？想研究下。。。感谢。。。请看到我

**Comment by CNLHB** [comment]
> 你好，大佬，研究了你的项目，觉得特体功能特别棒，很值得学习。研究接口文档和数据库，想请问一下，你会想恢复大的代码吗？谢谢。 。。请看我

会开源，半个月内吧，邮箱、短信服务的需要开通qq邮箱的权限和购买腾讯短信服务，到时我会在这个项目的下面放后端的链接
