### ISSUE TITLE
您好，`http://mobile.hfb.xquery.cn/`该链接在chrome和firefox浏览器“韩府”页面不显示内容，在微信内和safari可以显示

### ISSUE THREAD

**Issue by imingx** [CNLHB/ssk-hfb#6]
`link`: http://mobile.hfb.xquery.cn

# 不显示内容

## chrome

![image](https://user-images.githubusercontent.com/54981719/166551743-b0f9f1a1-3ce9-412c-93bf-50ed3531b068.png)

## firefox

![image](https://user-images.githubusercontent.com/54981719/166552056-17c75520-7f41-45c7-a4a1-01c945c70fe9.png)

# 显示内容

## 微信

![image](https://user-images.githubusercontent.com/54981719/166551804-a268780e-d0fe-4ece-a5e1-0e48362dd5a3.png)

## safari

![image](https://user-images.githubusercontent.com/54981719/166552015-4fa5f57d-57bf-4f9b-8fc1-338c9fdd4c60.png)

**Comment by CNLHB** [comment]
有一段时间没维护，可能是浏览器版本更新导致的，当时开发没这种问题

**Comment by imingx** [comment]
您好，感谢回复:>，已经大致定位和解决问题🧑‍💻，可能与`swipe`控件与Chrome&Firefox不兼容导致的，详细情况需要 @cpfy 定位细节问题之后再来回复。
